### ISSUE TITLE
Snuba, Glara and Tallor Label function generators

### ISSUE THREAD

**Issue by devashish-khatwani** [JieyuZ2/wrench#15]
In your paper you mention that Label Functions are critical to the overall performance of a WS system. Have you implemented this automated label function generators to compare these approaches to other approaches of creating Labeling functions automatically?

**Comment by JieyuZ2** [comment]
Hey @devashish-khatwani 

We do have implementations of our own labeling func generators in WRENCH, but we do not implement and compare them with other approaches because our generators are for studying the effect of labeling func. Thus, we could use all the ground truth labels to generate different types of LFs, while Snuba, Glara, and Tallor are all practical systems that aim for the real use cases where we would like to automate the generation of labeling func with still limited labeled data.
