### ISSUE TITLE
Multi-class with abstains

### ISSUE THREAD

**Issue by Abhinavb08** [JieyuZ2/wrench#20]
Thanks for adding your work on GitHub.

Question: I have a multiclass dataset that has 4 classes, and multiple weak labels. The weak labels mark '-1' for abstains. Does the weak supervision frameworks (such as FlyingSquid and others) used within the wrench library works for multiclass data along with abstains? 
If yes, then could you explain how do you aggregate weak labels for Multiclass dataset using FlyingSquid.

**Comment by JieyuZ2** [comment]
Hey

If I understand correctly, you're asking for the FlyingSquid and other methods for multiclass classification? The answer is yes, and for FlyingSquid, as shown in the source code, we build multiple one-vs-all label models because FlyingSquid can only handle binary classification. For other methods like Snorkel, they can work with multiclass classification naturally.
